# Generated by Django 3.1.7 on 2021-05-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name_plural': 'BookCategories'},
        ),
    ]
