# Generated by Django 3.1.7 on 2021-05-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210510_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='category_img_loc',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
