# Generated by Django 3.1.7 on 2021-05-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bookcategory_category_img_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='category_img_loc',
            field=models.FileField(default=0, upload_to='mysite/main/static/mysite/images'),
        ),
    ]
