# Generated by Django 3.1.7 on 2021-05-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210510_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='category_img_loc',
            field=models.FileField(upload_to='mysite/images'),
        ),
    ]
